name: MB3
favicon: null
layout_spectrum: 0.6473139843437821
typography_spectrum: 0.23219798877835274
title: MB3
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6177609944716096
  lightness: 0.13380143302492797
  saturation: 0.3867590678855777
  rhythmicContrast: 0.1261084896977991
purpose: []
